<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/MasterPage/Site1.Master" CodeBehind="CS.aspx.vb" Inherits="WebApplication.CS" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 340px;
            height: 340px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceholder" runat="server">
    <h1>
        Computer Science</h1>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        <b>Computer science</b> is the study of <a href="https://en.wikipedia.org/wiki/Process_(engineering)" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Process (engineering)">processes</a> that interact with <a href="https://en.wikipedia.org/wiki/Data" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Data">data</a> and that can be represented as data in the form of
        <a href="https://en.wikipedia.org/wiki/Computer_program" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer program">programs</a>. It enables the use of <a href="https://en.wikipedia.org/wiki/Algorithm" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Algorithm">algorithms</a> to
        <a href="https://en.wikipedia.org/wiki/Data_processing" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Data processing">manipulate</a>, <a href="https://en.wikipedia.org/wiki/Data_storage" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Data storage">store</a>, and
        <a href="https://en.wikipedia.org/wiki/Communication" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Communication">communicate</a> <a href="https://en.wikipedia.org/wiki/Digital_data" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Digital data">digital information</a>. A
        <a href="https://en.wikipedia.org/wiki/Computer_scientist" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer scientist">computer scientist</a> studies the <a href="https://en.wikipedia.org/wiki/Theory_of_computation" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Theory of computation">theory of computation</a> and the
        <a href="https://en.wikipedia.org/wiki/Software_design" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Software design">design</a> of <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Computer_system" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer system">computer systems</a>.<sup id="cite_ref-1" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Computer_science#cite_note-1" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[1]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        Its fields can be divided into theoretical and <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Practical_disciplines" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Practical disciplines">practical disciplines</a>. <a href="https://en.wikipedia.org/wiki/Computational_complexity_theory" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computational complexity theory">Computational complexity theory</a> is highly abstract, while
        <a href="https://en.wikipedia.org/wiki/Computer_graphics_(computer_science)" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer graphics (computer science)">computer graphics</a> emphasizes real-world applications. <a href="https://en.wikipedia.org/wiki/Programming_language_theory" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Programming language theory">Programming language theory</a> considers approaches to the description of computational processes, 
        while <a href="https://en.wikipedia.org/wiki/Software_engineering" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Software engineering">software engineering</a> involves the use of <a href="https://en.wikipedia.org/wiki/Programming_language" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Programming language">programming languages</a> and
        <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Complex_systems" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Complex systems">complex systems</a>. <a href="https://en.wikipedia.org/wiki/Human–computer_interaction" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Human–computer interaction">Human–computer interaction</a> considers the challenges in making computers useful, usable, and
        <a href="https://en.wikipedia.org/wiki/Computer_accessibility" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer accessibility">accessible</a>.
    </p>
    <p>
        <img alt="the father of computing" class="auto-style1" src="../Images/charles.png" /></p>
</asp:Content>
