<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/MasterPage/Site1.Master" CodeBehind="IS.aspx.vb" Inherits="WebApplication._IS" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 500px;
            height: 368px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContentPlaceholder" runat="server">
    <h1>
        Information Systems</h1>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        An <b>information system</b> (<b>IS</b>) is a formal, sociotechnical, organizational system designed to collect, process, store, and distribute <a href="https://en.wikipedia.org/wiki/Information" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Information">information</a>.<sup id="cite_ref-1" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-1" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[1]</a></sup> 
        In a <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Sociotechnical" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Sociotechnical">sociotechnical</a> perspective, information systems are composed by four components: task, people, structure (or roles), and technology.<sup id="cite_ref-Ohara_et_al._2-0" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-Ohara_et_al.-2" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[2]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        A <b>computer information system</b> is a system composed of people and computers that processes or interprets information.<sup id="cite_ref-3" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-3" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[3]</a></sup><sup id="cite_ref-4" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-4" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[4]</a></sup><sup id="cite_ref-5" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-5" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[5]</a></sup><sup id="cite_ref-6" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-6" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[6]</a></sup> 
        The term is also sometimes used in more restricted senses to refer to only the software used to run a computerized database or to refer to only a <a href="https://en.wikipedia.org/wiki/Computer" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer">computer system</a>.
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        <b>Information Systems</b> is an academic study of systems with a specific reference to information and the complementary networks of hardware and software that people and organizations use to collect, filter, process, create and also distribute <a href="https://en.wikipedia.org/wiki/Data_(computing)" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Data (computing)">data</a>. An emphasis is placed on an information system having a definitive boundary, users, processors, storage, inputs, outputs and the aforementioned communication networks.<sup id="cite_ref-7" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-7" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[7]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        Any specific information system aims to support operations, management and <a href="https://en.wikipedia.org/wiki/Decision-making" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Decision-making">decision-making</a>.<sup id="cite_ref-8" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-8" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[8]</a></sup><sup id="cite_ref-9" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-9" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[9]</a></sup> 
        An information system is the <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Information_and_communication_technology" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Information and communication technology">information and communication technology</a> (ICT) that an organization uses, and also the way in which people interact with this technology in support of business processes.<sup id="cite_ref-10" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-10" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[10]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        Some authors make a clear distinction between information systems, <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Computer_system" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Computer system">computer systems</a>, and <a href="https://en.wikipedia.org/wiki/Business_process" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Business process">business processes</a>. Information systems typically include an ICT component but are not purely concerned with 
        ICT, focusing instead on the end use of <a href="https://en.wikipedia.org/wiki/Information_technology" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Information technology">information technology</a>. Information systems are also different from business processes. Information systems help to control the performance of business processes.<sup id="cite_ref-11" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-11" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[11]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        Alter<sup id="cite_ref-12" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-12" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[12]</a></sup><sup id="cite_ref-13" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-13" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[13]</a></sup> 
        argues for advantages of viewing an information system as a special type of <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Work_system" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Work system">work system</a>. A work system is a system in which humans or machines perform processes and activities using resources to produce specific products or services for customers. An information system is a work system whose activities are devoted to capturing, transmitting, storing, retrieving, manipulating and displaying information.<sup id="cite_ref-14" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-14" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;">[14]</a></sup>
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        As such, information systems inter-relate with <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Data_systems" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Data systems">data systems</a> on the one hand and activity systems on the other. An information system is a form of <a href="https://en.wikipedia.org/wiki/Communication" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Communication">communication</a> system in which data represent and are processed 
        as a form of social memory. An information system can also be considered a semi-<a href="https://en.wikipedia.org/wiki/Formal_language" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Formal language">formal language</a> which supports human decision making and action.
    </p>
    <p style="color: rgb(32, 33, 34); font-family: sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: 400; letter-spacing: normal; margin-bottom: 0.5em; margin-left: 0px; margin-right: 0px; margin-top: 0.5em; orphans: 2; text-align: left; text-decoration: none; text-indent: 0px; text-transform: none; -webkit-text-stroke-width: 0px; white-space: normal; word-spacing: 0px;">
        Information systems are the primary focus of study for <a class="mw-redirect" href="https://en.wikipedia.org/wiki/Organizational_informatics" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: none;" title="Organizational informatics">organizational informatics</a>.<sup id="cite_ref-15" class="reference" style="font-size: 80%; font-style: normal; font-weight: normal; line-height: 1; white-space: nowrap;"><a href="https://en.wikipedia.org/wiki/Information_system#cite_note-15" style="background-attachment: scroll; background-clip: border-box; background-color: transparent; background-image: none; background-origin: padding-box; background-position-x: 0%; background-position-y: 0%; background-repeat: repeat; background-size: auto; color: rgb(6, 69, 173); text-decoration: underline;">[15</a></sup></p>
    <p>
        <img alt="a four level hierarchy" class="auto-style1" src="../Images/is.png" /></p>
</asp:Content>
